### ISSUE TITLE
using jquery-animate-numbers with input ?

### ISSUE THREAD

**Issue by YouSour** [talmand/jquery-animate-numbers#4]
i just using  jquery-animate-numbers , i don't how to use with input , any idea ?

**Comment by talmand** [comment]
I didn't think of that as a use case. You would have to make your own version of the function so that it handles the val() of the input instead of text(). Just replace every instance of text() with val() and take out the comma part as I doubt you would need it.

Here's an example: http://jsfiddle.net/talmand/vx89z6br/

If you still need the function to work on other regular text elements then duplicate and rename to have a secondary version on the same page.

I'll have to consider updating the thing to check for inputs. Let me know if you have any other issues.

**Comment by YouSour** [comment]
thank you for info :+1:
